import type { Drill } from "../types";

export const DRILLS: Drill[] = [
  // === SKATING ===
  {
    id: "skating_forward",
    name: "Framåtåkning – grundsteg",
    category: "skating",
    position: ["Forward", "Center", "Back", "Goalie"],
    level: "beginner",
    cues: [
      "Knän böjda, tyngdpunkt låg",
      "Skjut ut med utsidan av bladet",
      "Full extension vid varje steg",
      "Armarna svingar i takt med benen",
    ],
    progressions: [{ drillId: "skating_stride_power", unlockAfter: 5 }],
    defaultDuration: 15,
  },
  {
    id: "skating_backward",
    name: "Bakåtåkning",
    category: "skating",
    position: ["Forward", "Center", "Back", "Goalie"],
    level: "beginner",
    cues: [
      "C-cut med ena foten i taget",
      "Tyngdpunkten lätt framåtlutad (bakåt i rörtriktan)",
      "Håll koll på isen bakom dig med ögonkontakt",
      "Höfterna låga, balansen mitt över skridskorna",
    ],
    progressions: [{ drillId: "skating_crossovers_back", unlockAfter: 5 }],
    defaultDuration: 15,
  },
  {
    id: "skating_crossovers_fwd",
    name: "Crossovers framåt (vänster/höger)",
    category: "skating",
    position: ["Forward", "Center", "Back"],
    level: "intermediate",
    cues: [
      "Ytterben kliver över innerben",
      "Innerbenet skjuter ut för att ge kraft",
      "Luta in i kurvan — tryck utåt med ytterflänsen",
      "Håll rygg rak, inte frambockad",
    ],
    progressions: [{ drillId: "skating_edge_work", unlockAfter: 8 }],
    defaultDuration: 15,
  },
  {
    id: "skating_crossovers_back",
    name: "Crossovers bakåt",
    category: "skating",
    position: ["Back", "Goalie"],
    level: "intermediate",
    cues: [
      "Starta med en C-cut bakåt, kliv sedan över",
      "Håll ögonen framåt (mot motståndaren)",
      "Djupa knäböj för kraft och balans",
      "Jämn hastighet, inga ryckiga rörelser",
    ],
    progressions: [],
    defaultDuration: 15,
  },
  {
    id: "skating_tight_turns",
    name: "Tight turns",
    category: "skating",
    position: ["Forward", "Center", "Back"],
    level: "intermediate",
    cues: [
      "Sänk tyngdpunkten precis innan svängen",
      "Inre foten leder, yttre ger kraft",
      "Håll pucken nära kroppen i svängen",
      "Accelerera ur svängen — full steg direkt ut",
    ],
    progressions: [{ drillId: "skating_mohawk", unlockAfter: 10 }],
    defaultDuration: 10,
  },
  {
    id: "skating_mohawk",
    name: "Mohawk-vändning",
    category: "skating",
    position: ["Forward", "Center"],
    level: "advanced",
    cues: [
      "Rotera foten 180° på plats — ingen extra steg",
      "Tyngden överflytt smidigt mellan fötterna",
      "Övre kroppen pekar i rörelseriktningen under hela rörelsen",
      "Öva långsamt — hastighet kommer med muskelminne",
    ],
    progressions: [],
    defaultDuration: 10,
  },
  {
    id: "skating_hockey_stop",
    name: "Hockey-stopp (båda sidor)",
    category: "skating",
    position: ["Forward", "Center", "Back", "Goalie"],
    level: "intermediate",
    cues: [
      "Rotera höfterna 90° — inte bara fötterna",
      "Tryck ned på bladet med hela foten för bita",
      "Knän absorberar stöten — håll dem böjda",
      "Öva svag sida lika mycket som stark sida",
    ],
    progressions: [],
    defaultDuration: 10,
  },
  {
    id: "skating_edge_work",
    name: "Edge-arbete (inre/yttre)",
    category: "skating",
    position: ["Forward", "Center", "Back"],
    level: "intermediate",
    cues: [
      "Isolera inre/yttre kant — en fot i taget",
      "Knäet pekar åt samma håll som kanten",
      "Överdriva kantanvändningen i övningen",
      "Mät att du lämnar djupa spår i isen",
    ],
    progressions: [],
    defaultDuration: 15,
  },
  {
    id: "skating_stride_power",
    name: "Stride power – explosivitet",
    category: "skating",
    position: ["Forward", "Center", "Back"],
    level: "advanced",
    cues: [
      "Knäböj djupt vid push-off — inte ytligt",
      "Sträck fullt ut i höft, knä och fotled",
      "Håll isens kontakt längst in i steget",
      "Återhämta benet snabbt under kroppen",
    ],
    progressions: [],
    defaultDuration: 15,
  },
  {
    id: "skating_transitions",
    name: "Forward-till-bakåt övergångar",
    category: "skating",
    position: ["Forward", "Center", "Back"],
    level: "advanced",
    cues: [
      "Pivot-foten tar ansvaret för vändningen",
      "Övre kroppen vrider sig minimalt",
      "Inga döda steg — flöda direkt in i bakåtåkning",
      "Öva båda sidor — svag sida oftare",
    ],
    progressions: [],
    defaultDuration: 10,
  },

  // === SHOOTING ===
  {
    id: "shot_wrist",
    name: "Wrist shot",
    category: "shooting",
    position: ["Forward", "Center", "Back"],
    level: "beginner",
    cues: [
      "Pucken ligger på bakre delen av bladet — rulla fram",
      "Tyngdöverföring från bakfot till framfot",
      "Bladets följ-through pekar på målet",
      "Nedre handen vrider — övre handen styr riktningen",
    ],
    progressions: [{ drillId: "shot_snap", unlockAfter: 10 }],
    defaultDuration: 15,
  },
  {
    id: "shot_snap",
    name: "Snap shot",
    category: "shooting",
    position: ["Forward", "Center"],
    level: "intermediate",
    cues: [
      "Pucken precis framför framfoten",
      "Snabb handledsvridning — inte full svängkraft",
      "Flexen används aktivt — böj klubban mot isen",
      "Snabb release — kortare lösning än wrist",
    ],
    progressions: [{ drillId: "shot_one_timer", unlockAfter: 15 }],
    defaultDuration: 15,
  },
  {
    id: "shot_slap",
    name: "Slap shot",
    category: "shooting",
    position: ["Back", "Forward"],
    level: "intermediate",
    cues: [
      "Träffa isen 2–3 cm bakom pucken",
      "Tyngd på framfoten vid kontakt",
      "Maximal klabbflex — böj mot isen",
      "Följ-through högt, peka på målet",
    ],
    progressions: [],
    defaultDuration: 15,
  },
  {
    id: "shot_backhand",
    name: "Backhand shot",
    category: "shooting",
    position: ["Forward", "Center"],
    level: "beginner",
    cues: [
      "Pucken på bladets backhand-del",
      "Lyft framänden av bladet vid release",
      "Rotera höfterna in i skottet",
      "Öva högt och lågt mot nätet",
    ],
    progressions: [],
    defaultDuration: 10,
  },
  {
    id: "shot_one_timer",
    name: "One-timer",
    category: "shooting",
    position: ["Forward", "Center"],
    level: "advanced",
    cues: [
      "Läs passningens riktning tidigt — flytta fötterna",
      "Öppna höfterna mot passen",
      "Skjut i samma rörelse som pucken anländer",
      "Öga på pucken hela vägen till bladet",
    ],
    progressions: [],
    defaultDuration: 15,
  },
  {
    id: "shot_off_foot",
    name: "Skott från fel fot",
    category: "shooting",
    position: ["Forward", "Center"],
    level: "advanced",
    cues: [
      "Tyngd på bakre foten (oortodoxt) — öva att kompensera",
      "Överkroppsrotation viktigare när fötterna inte hjälper",
      "Kortare backswing för snabbare release",
      "Nyckel: inte ge försvararen tid att anpassa sig",
    ],
    progressions: [],
    defaultDuration: 10,
  },
  {
    id: "shot_in_stride",
    name: "Skott i fart",
    category: "shooting",
    position: ["Forward", "Center"],
    level: "advanced",
    cues: [
      "Inte avbryta steget — skjut mitt i rörelsen",
      "Tyngdöverföring sker naturligt med rörelsen",
      "Håll axlarna kvadrerade mot målet",
      "Snabbt utsläpp är viktigare än kraften",
    ],
    progressions: [],
    defaultDuration: 15,
  },
  {
    id: "shot_deflection",
    name: "Deflektioner",
    category: "shooting",
    position: ["Forward", "Center"],
    level: "advanced",
    cues: [
      "Stå framför nätet, klubba vid isen",
      "Vrid bara handleden — ingen stor rörelse",
      "Titta på pucken, inte på målvakten",
      "Röj en position framför målet och håll den",
    ],
    progressions: [],
    defaultDuration: 10,
  },
  {
    id: "shot_screen",
    name: "Screen shot",
    category: "shooting",
    position: ["Forward", "Center"],
    level: "intermediate",
    cues: [
      "Screenspelaren: stå stadig, tappa inte positionen",
      "Skyttaren: sikt precis förbi skärmen",
      "Låg, hård skivva är enklare att deflektera",
      "Kommunicera med skyttaren om timing",
    ],
    progressions: [],
    defaultDuration: 10,
  },

  // === PASSING ===
  {
    id: "pass_forehand",
    name: "Forehand-pass",
    category: "passing",
    position: ["Forward", "Center", "Back", "Goalie"],
    level: "beginner",
    cues: [
      "Pucken rullas från bakfoten av bladet",
      "Peka följ-through på mottagaren",
      "Passningshastigheten anpassas efter distansen",
      "Platt mot isen — inte lyft",
    ],
    progressions: [{ drillId: "pass_saucer", unlockAfter: 8 }],
    defaultDuration: 15,
  },
  {
    id: "pass_backhand",
    name: "Backhand-pass",
    category: "passing",
    position: ["Forward", "Center", "Back"],
    level: "beginner",
    cues: [
      "Pucken bakom kroppen på backhand-sidan",
      "Kort, stabil rörelse — inte stor svängning",
      "Ögon på mottagaren, inte på pucken",
      "Överskottsenergi absorberas av handleden",
    ],
    progressions: [],
    defaultDuration: 10,
  },
  {
    id: "pass_saucer",
    name: "Saucer pass (över skridskor)",
    category: "passing",
    position: ["Forward", "Center"],
    level: "intermediate",
    cues: [
      "Vrida handleden för att ge pucken snurr",
      "Lyftet sker med fingertoppen av bladet",
      "Sikta på mottagarens blade — inte knäna",
      "Öva avstånd: 3m, 5m, 8m",
    ],
    progressions: [],
    defaultDuration: 10,
  },
  {
    id: "pass_give_and_go",
    name: "Give-and-go",
    category: "passing",
    position: ["Forward", "Center"],
    level: "intermediate",
    cues: [
      "Passa och accelerera omedelbart",
      "Kontaktpunkt: ta emot i fart, inte stillastående",
      "Kommunicera i förväg — ögonkontakt",
      "Timing är allt — passa när mottagaren är redo",
    ],
    progressions: [],
    defaultDuration: 10,
  },
  {
    id: "pass_no_look",
    name: "No-look pass",
    category: "passing",
    position: ["Forward", "Center"],
    level: "advanced",
    cues: [
      "Ögonkontakt med lockbitet — titta åt fel håll",
      "Periferseende: känn av medspelaren utan att titta",
      "Kort, precis rörelse — inget telegraferat",
      "Säkerhet före show: testa bara i rätt läge",
    ],
    progressions: [],
    defaultDuration: 10,
  },
  {
    id: "pass_board",
    name: "Bandpass",
    category: "passing",
    position: ["Forward", "Center", "Back"],
    level: "intermediate",
    cues: [
      "Beräkna studsvinkel: infall = utfall",
      "Passens kraft påverkar studsens avstånd",
      "Öva längs med bandet och på diagonala vinklar",
      "Mottagaren rör sig i tid med passens ankomst",
    ],
    progressions: [],
    defaultDuration: 10,
  },

  // === PUCK HANDLING ===
  {
    id: "puck_figure8",
    name: "Puck-handling figur-8",
    category: "puck",
    position: ["Forward", "Center"],
    level: "beginner",
    cues: [
      "Händerna mjuka — inte krampaktigt grepp",
      "Rör pucken med bladets toe och heel",
      "Tyngd framåt, inte bakåt på klackarna",
      "Öka tempot gradvis varje omgång",
    ],
    progressions: [{ drillId: "puck_toe_drag", unlockAfter: 10 }],
    defaultDuration: 10,
  },
  {
    id: "puck_toe_drag",
    name: "Toe drag",
    category: "puck",
    position: ["Forward", "Center"],
    level: "intermediate",
    cues: [
      "Dra pucken med bladets toe (spets)",
      "Överkroppsrotation maskerar rörelsen",
      "Snabb avslutning — skjut eller passa direkt ur dragets",
      "Håll bladet nära isen under dragets",
    ],
    progressions: [{ drillId: "puck_dangle", unlockAfter: 15 }],
    defaultDuration: 10,
  },
  {
    id: "puck_between_legs",
    name: "Between-the-legs",
    category: "puck",
    position: ["Forward"],
    level: "advanced",
    cues: [
      "Bred skridskobredd för utrymme",
      "Pucken passeras under kroppen med en snabb handledsvridning",
      "Kroppen täcker rörelsen — keep defensive",
      "Öva utan motståndar-pressure på off-ice first",
    ],
    progressions: [],
    defaultDuration: 10,
  },
  {
    id: "puck_dangle",
    name: "Fint och dribbling",
    category: "puck",
    position: ["Forward", "Center"],
    level: "advanced",
    cues: [
      "Finta med ögon och axlar, inte bara pucken",
      "Commit motståndaren — vänta tills han reagerar",
      "Korta, snabba rörelser slår långa svepningar",
      "Avsluta alltid — inte bara visa upp",
    ],
    progressions: [],
    defaultDuration: 10,
  },
  {
    id: "puck_protected",
    name: "Protected puck / hyllhållning",
    category: "puck",
    position: ["Forward", "Center", "Back"],
    level: "intermediate",
    cues: [
      "Kroppen mellan motståndaren och pucken",
      "Lågt tyngdpunkt — bred bas",
      "En hand på klubban räcker ibland",
      "Sök stödet av bandet eller en medspelare",
    ],
    progressions: [],
    defaultDuration: 10,
  },

  // === OFF-ICE ===
  {
    id: "office_shooting_pad",
    name: "Shooting pad – wrist/snap-serie",
    category: "offIce",
    position: ["Forward", "Center", "Back"],
    level: "beginner",
    cues: [
      "Simulera rätt vikt-transfer på platta underlaget",
      "Öva både forehand och backhand",
      "Fokusera på handledshastighet och release-punkt",
      "Filma profilen — kontrollera seguansen",
    ],
    progressions: [],
    defaultDuration: 20,
  },
  {
    id: "office_slick_board",
    name: "Slick board stickhandling",
    category: "offIce",
    position: ["Forward", "Center"],
    level: "intermediate",
    cues: [
      "Händerna mjuka och avslappnade",
      "Toppen och botten av figur-8",
      "Ögonen upp — inte på pucken",
      "Variera hastighet och mönster",
    ],
    progressions: [],
    defaultDuration: 15,
  },
  {
    id: "office_ladder_agility",
    name: "Stegladder-agilitet",
    category: "offIce",
    position: ["Forward", "Center", "Back", "Goalie"],
    level: "beginner",
    cues: [
      "Hög knälyftning — inte slarv",
      "Armarnas rörelse driver takten",
      "Helar-toe-mönster: heel-in, toe-out",
      "Öka hastighet bara när mönstret sitter",
    ],
    progressions: [],
    defaultDuration: 15,
  },
  {
    id: "office_balance_board",
    name: "Balance board – ett-bens-balans",
    category: "offIce",
    position: ["Forward", "Center", "Back", "Goalie"],
    level: "intermediate",
    cues: [
      "Fokusera ett stillastående punkt framför dig",
      "Mikro-korrektioner med foten, inte kroppen",
      "Lägg till arm-rörelser för progression",
      "Öva med ögonen stängda när du behärskar det",
    ],
    progressions: [],
    defaultDuration: 10,
  },
  {
    id: "office_mobility",
    name: "Hockeyspecifik mobilitet",
    category: "offIce",
    position: ["Forward", "Center", "Back", "Goalie"],
    level: "beginner",
    cues: [
      "Hip flexor stretch: knä i golvet, framben 90°",
      "Thorakal rotation: stolt bröst, rotera axlarna",
      "Groin stretch med rotation",
      "Håll varje position 30–45 sekunder",
    ],
    progressions: [],
    defaultDuration: 20,
  },

  // === GOALIE ===
  {
    id: "goalie_butterfly",
    name: "Butterfly – drop och återhämtning",
    category: "goalie",
    position: ["Goalie"],
    level: "beginner",
    cues: [
      "Knäna faller inåt och nedåt — inte bakåt",
      "Blockerare och handske täcker de nedre hörnen",
      "Stå upp snabbt med ett C-cut",
      "Håll ryggen upprätt, inte framåtlutad",
    ],
    progressions: [{ drillId: "goalie_rvh", unlockAfter: 10 }],
    defaultDuration: 15,
  },
  {
    id: "goalie_t_push",
    name: "T-push lateral förflyttning",
    category: "goalie",
    position: ["Goalie"],
    level: "beginner",
    cues: [
      "Pushfoten plantad med full kant",
      "Glidfoten parallell med målet",
      "Skjuta kraftfullt — inte trippla",
      "Stanna exakt i post-position",
    ],
    progressions: [{ drillId: "goalie_butterfly", unlockAfter: 5 }],
    defaultDuration: 15,
  },
  {
    id: "goalie_rvh",
    name: "RVH (Reverse VH) post-position",
    category: "goalie",
    position: ["Goalie"],
    level: "advanced",
    cues: [
      "Ena skridska mot posten — kant mot isen",
      "Andra knäet ned — seal off the ice",
      "Blockerare täcker övre hörnet",
      "Var redo att gå ut — inte bara fastna i posten",
    ],
    progressions: [],
    defaultDuration: 10,
  },
  {
    id: "goalie_recovery",
    name: "Återhämtning från butterfly",
    category: "goalie",
    position: ["Goalie"],
    level: "intermediate",
    cues: [
      "C-cut med ena foten ger snabb resesning",
      "Händerna framåt vid återhämtning",
      "Titta på pucken under hela återhämtningen",
      "Öva ensidigt: vänster C-cut, höger C-cut",
    ],
    progressions: [],
    defaultDuration: 15,
  },
  {
    id: "goalie_glove_blocker",
    name: "Handske och blockerare – grundpositioner",
    category: "goalie",
    position: ["Goalie"],
    level: "beginner",
    cues: [
      "Handske framåt och nedåt — inte vid höften",
      "Blockeraren vinklad utåt för att deflektera",
      "Kolla positionerna i spegel regelbundet",
      "Mjuka händer — absorbera inte stöta av",
    ],
    progressions: [],
    defaultDuration: 10,
  },
];

export function getDrillById(id: string): Drill | undefined {
  return DRILLS.find((d) => d.id === id);
}

export function getDrillsByCategory(category: Drill["category"]): Drill[] {
  return DRILLS.filter((d) => d.category === category);
}

export function getDrillsByPosition(position: string): Drill[] {
  return DRILLS.filter((d) => d.position.includes(position as Drill["position"][number]));
}
